[build]
  command = "pnpm build"
  publish = ".netlify/output"

[dev]
  command = "pnpm dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200