/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SalesPipelineRouteImport } from './routes/sales.pipeline'
import { Route as ProjectsClientSlugRouteImport } from './routes/projects.$clientSlug'
import { Route as FinancialsReportsRouteImport } from './routes/financials.reports'
import { Route as FinancialsPaymentsRouteImport } from './routes/financials.payments'
import { Route as FinancialsInvoicesRouteImport } from './routes/financials.invoices'
import { Route as FinancialsEstimatesRouteImport } from './routes/financials.estimates'
import { Route as AutomationWorkflowsRouteImport } from './routes/automation.workflows'
import { Route as AutomationWorkflowsIndexRouteImport } from './routes/automation.workflows.index'
import { Route as AutomationWorkflowsWorkflowIdRouteImport } from './routes/automation.workflows.$workflowId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales/pipeline',
  path: '/sales/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsClientSlugRoute = ProjectsClientSlugRouteImport.update({
  id: '/projects/$clientSlug',
  path: '/projects/$clientSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsReportsRoute = FinancialsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinancialsRoute,
} as any)
const FinancialsPaymentsRoute = FinancialsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinancialsRoute,
} as any)
const FinancialsInvoicesRoute = FinancialsInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinancialsRoute,
} as any)
const FinancialsEstimatesRoute = FinancialsEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => FinancialsRoute,
} as any)
const AutomationWorkflowsRoute = AutomationWorkflowsRouteImport.update({
  id: '/automation/workflows',
  path: '/automation/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationWorkflowsIndexRoute =
  AutomationWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AutomationWorkflowsRoute,
  } as any)
const AutomationWorkflowsWorkflowIdRoute =
  AutomationWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AutomationWorkflowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/financials': typeof FinancialsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRouteWithChildren
  '/automation/workflows': typeof AutomationWorkflowsRouteWithChildren
  '/financials/estimates': typeof FinancialsEstimatesRoute
  '/financials/invoices': typeof FinancialsInvoicesRoute
  '/financials/payments': typeof FinancialsPaymentsRoute
  '/financials/reports': typeof FinancialsReportsRoute
  '/projects/$clientSlug': typeof ProjectsClientSlugRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/projects/': typeof ProjectsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/automation/workflows/': typeof AutomationWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/financials': typeof FinancialsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRouteWithChildren
  '/financials/estimates': typeof FinancialsEstimatesRoute
  '/financials/invoices': typeof FinancialsInvoicesRoute
  '/financials/payments': typeof FinancialsPaymentsRoute
  '/financials/reports': typeof FinancialsReportsRoute
  '/projects/$clientSlug': typeof ProjectsClientSlugRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/projects': typeof ProjectsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/automation/workflows': typeof AutomationWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/financials': typeof FinancialsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRouteWithChildren
  '/automation/workflows': typeof AutomationWorkflowsRouteWithChildren
  '/financials/estimates': typeof FinancialsEstimatesRoute
  '/financials/invoices': typeof FinancialsInvoicesRoute
  '/financials/payments': typeof FinancialsPaymentsRoute
  '/financials/reports': typeof FinancialsReportsRoute
  '/projects/$clientSlug': typeof ProjectsClientSlugRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/projects/': typeof ProjectsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/automation/workflows/': typeof AutomationWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/calendar'
    | '/contacts'
    | '/financials'
    | '/inbox'
    | '/settings'
    | '/automation/workflows'
    | '/financials/estimates'
    | '/financials/invoices'
    | '/financials/payments'
    | '/financials/reports'
    | '/projects/$clientSlug'
    | '/sales/pipeline'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/team'
    | '/projects/'
    | '/automation/workflows/$workflowId'
    | '/automation/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/calendar'
    | '/contacts'
    | '/financials'
    | '/inbox'
    | '/settings'
    | '/financials/estimates'
    | '/financials/invoices'
    | '/financials/payments'
    | '/financials/reports'
    | '/projects/$clientSlug'
    | '/sales/pipeline'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/team'
    | '/projects'
    | '/automation/workflows/$workflowId'
    | '/automation/workflows'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/calendar'
    | '/contacts'
    | '/financials'
    | '/inbox'
    | '/settings'
    | '/automation/workflows'
    | '/financials/estimates'
    | '/financials/invoices'
    | '/financials/payments'
    | '/financials/reports'
    | '/projects/$clientSlug'
    | '/sales/pipeline'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/team'
    | '/projects/'
    | '/automation/workflows/$workflowId'
    | '/automation/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CalendarRoute: typeof CalendarRoute
  ContactsRoute: typeof ContactsRoute
  FinancialsRoute: typeof FinancialsRouteWithChildren
  InboxRoute: typeof InboxRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AutomationWorkflowsRoute: typeof AutomationWorkflowsRouteWithChildren
  ProjectsClientSlugRoute: typeof ProjectsClientSlugRoute
  SalesPipelineRoute: typeof SalesPipelineRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sales/pipeline': {
      id: '/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$clientSlug': {
      id: '/projects/$clientSlug'
      path: '/projects/$clientSlug'
      fullPath: '/projects/$clientSlug'
      preLoaderRoute: typeof ProjectsClientSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials/reports': {
      id: '/financials/reports'
      path: '/reports'
      fullPath: '/financials/reports'
      preLoaderRoute: typeof FinancialsReportsRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/financials/payments': {
      id: '/financials/payments'
      path: '/payments'
      fullPath: '/financials/payments'
      preLoaderRoute: typeof FinancialsPaymentsRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/financials/invoices': {
      id: '/financials/invoices'
      path: '/invoices'
      fullPath: '/financials/invoices'
      preLoaderRoute: typeof FinancialsInvoicesRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/financials/estimates': {
      id: '/financials/estimates'
      path: '/estimates'
      fullPath: '/financials/estimates'
      preLoaderRoute: typeof FinancialsEstimatesRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/automation/workflows': {
      id: '/automation/workflows'
      path: '/automation/workflows'
      fullPath: '/automation/workflows'
      preLoaderRoute: typeof AutomationWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/workflows/': {
      id: '/automation/workflows/'
      path: '/'
      fullPath: '/automation/workflows/'
      preLoaderRoute: typeof AutomationWorkflowsIndexRouteImport
      parentRoute: typeof AutomationWorkflowsRoute
    }
    '/automation/workflows/$workflowId': {
      id: '/automation/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/automation/workflows/$workflowId'
      preLoaderRoute: typeof AutomationWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AutomationWorkflowsRoute
    }
  }
}

interface FinancialsRouteChildren {
  FinancialsEstimatesRoute: typeof FinancialsEstimatesRoute
  FinancialsInvoicesRoute: typeof FinancialsInvoicesRoute
  FinancialsPaymentsRoute: typeof FinancialsPaymentsRoute
  FinancialsReportsRoute: typeof FinancialsReportsRoute
}

const FinancialsRouteChildren: FinancialsRouteChildren = {
  FinancialsEstimatesRoute: FinancialsEstimatesRoute,
  FinancialsInvoicesRoute: FinancialsInvoicesRoute,
  FinancialsPaymentsRoute: FinancialsPaymentsRoute,
  FinancialsReportsRoute: FinancialsReportsRoute,
}

const FinancialsRouteWithChildren = FinancialsRoute._addFileChildren(
  FinancialsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface AutomationWorkflowsRouteChildren {
  AutomationWorkflowsWorkflowIdRoute: typeof AutomationWorkflowsWorkflowIdRoute
  AutomationWorkflowsIndexRoute: typeof AutomationWorkflowsIndexRoute
}

const AutomationWorkflowsRouteChildren: AutomationWorkflowsRouteChildren = {
  AutomationWorkflowsWorkflowIdRoute: AutomationWorkflowsWorkflowIdRoute,
  AutomationWorkflowsIndexRoute: AutomationWorkflowsIndexRoute,
}

const AutomationWorkflowsRouteWithChildren =
  AutomationWorkflowsRoute._addFileChildren(AutomationWorkflowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CalendarRoute: CalendarRoute,
  ContactsRoute: ContactsRoute,
  FinancialsRoute: FinancialsRouteWithChildren,
  InboxRoute: InboxRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AutomationWorkflowsRoute: AutomationWorkflowsRouteWithChildren,
  ProjectsClientSlugRoute: ProjectsClientSlugRoute,
  SalesPipelineRoute: SalesPipelineRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
